version: "3.9"

services:
  synchro:
    build:
      context: .
      dockerfile: docker/Dockerfile
    deploy:
      replicas: 10
    ports:
      - "8001-8010:8000"
    volumes:
      - ./app/sync_files:/usr/src/app/app/sync_files
 